[package]
name = "partition-iterator"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/microgravitas/partition-iterator"
readme = "README.md"

keywords = ["mathematics"]

[dependencies]
